"""refactor teams and matches

Revision ID: 335e60fb8393
Revises: fbb504060d3a
Create Date: 2026-02-28 14:50:18.140114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335e60fb8393'
down_revision: Union[str, Sequence[str], None] = 'fbb504060d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('team_home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team_away_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('match_date', sa.DateTime(), nullable=True))
    op.drop_column('matches', 'score_away')
    op.drop_column('matches', 'date')
    op.drop_column('matches', 'score_home')
    op.add_column('news', sa.Column('content', sa.String(), nullable=True))
    op.add_column('news', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.drop_column('news', 'author')
    op.drop_column('news', 'description')
    op.drop_column('news', 'date')
    op.drop_column('news', 'url_path')
    op.alter_column('teams', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_teams_team'), table_name='teams')
    op.create_index(op.f('ix_teams_team'), 'teams', ['team'], unique=True)
    op.create_index(op.f('ix_teams_region'), 'teams', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_region'), table_name='teams')
    op.drop_index(op.f('ix_teams_team'), table_name='teams')
    op.create_index(op.f('ix_teams_team'), 'teams', ['team'], unique=False)
    op.alter_column('teams', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('news', sa.Column('url_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_column('news', 'created_at')
    op.drop_column('news', 'content')
    op.add_column('matches', sa.Column('score_home', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('score_away', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'match_date')
    op.drop_column('matches', 'team_away_score')
    op.drop_column('matches', 'team_home_score')
    # ### end Alembic commands ###
