"""add news table

Revision ID: 6c63358f9d9c
Revises: 8cf27655586c
Create Date: 2026-03-01 12:13:20.870335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c63358f9d9c'
down_revision: Union[str, Sequence[str], None] = '8cf27655586c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('news', sa.Column('author', sa.String(), nullable=True))
    op.add_column('news', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_url')
    op.drop_column('news', 'author')
    op.drop_column('news', 'summary')
    # ### end Alembic commands ###
