"""add logo to tournament In database too

Revision ID: 8cf27655586c
Revises: f8bddfe12002
Create Date: 2026-03-01 11:06:56.717666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf27655586c'
down_revision: Union[str, Sequence[str], None] = 'f8bddfe12002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'logo_url')
    # ### end Alembic commands ###
