"""update_tournament_fields

Revision ID: 906b4ce225fc
Revises: d692d5506700
Create Date: 2026-02-28 22:17:53.928325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906b4ce225fc'
down_revision: Union[str, Sequence[str], None] = 'd692d5506700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('location', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tournaments', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('tournaments', sa.Column('prize_pool', sa.BigInteger(), nullable=True))
    op.drop_column('tournaments', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'prize_pool')
    op.drop_column('tournaments', 'end_date')
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'location')
    # ### end Alembic commands ###
