"""Added tournament foreig key to matches and tournament table

Revision ID: d692d5506700
Revises: 335e60fb8393
Create Date: 2026-02-28 22:03:31.292977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd692d5506700'
down_revision: Union[str, Sequence[str], None] = '335e60fb8393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'tournament_id')
    # ### end Alembic commands ###
