"""changes team model

Revision ID: fbb504060d3a
Revises: 64aad0b2ac93
Create Date: 2026-02-28 14:43:50.937585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb504060d3a'
down_revision: Union[str, Sequence[str], None] = '64aad0b2ac93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('teams', 'team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_teams_team'), 'teams', ['team'], unique=False)
    op.drop_column('teams', 'last_played_logo')
    op.drop_column('teams', 'rank')
    op.drop_column('teams', 'record')
    op.drop_column('teams', 'logo')
    op.drop_column('teams', 'earnings')
    op.drop_column('teams', 'last_played')
    op.drop_column('teams', 'last_played_team')
    op.drop_column('teams', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('last_played_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('last_played', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('earnings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('record', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('rank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('last_played_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_teams_team'), table_name='teams')
    op.alter_column('teams', 'team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('teams', 'is_active')
    op.drop_column('teams', 'logo_url')
    # ### end Alembic commands ###
